/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "border-strong": "#cbd5e1",
        "inverse-on-surface": "#f2f0ed",
        "secondary-fixed-dim": "#b9c7df",
        "surface-container-low": "#f5f3f0",
        "primary-container": "#16324f",
        "outline": "#74777e",
        "on-primary-container": "#809abd",
        "inverse-primary": "#aec9ed",
        "background": "#fbf9f6",
        "tertiary-container": "#482900",
        "surface-card": "#ffffff",
        "surface": "#fbf9f6",
        "tertiary-fixed": "#ffddbb",
        "tertiary": "#2c1700",
        "on-primary-fixed": "#001d37",
        "tertiary-fixed-dim": "#ffb868",
        "error-container": "#ffdad6",
        "surface-dim": "#dbdad7",
        "on-primary-fixed-variant": "#2e4867",
        "on-secondary": "#ffffff",
        "on-secondary-fixed-variant": "#3a485b",
        "on-secondary-container": "#57657a",
        "on-error": "#ffffff",
        "primary-fixed-dim": "#aec9ed",
        "secondary": "#515f74",
        "on-background": "#1b1c1a",
        "primary": "#001d37",
        "on-surface": "#1b1c1a",
        "secondary-fixed": "#d5e3fc",
        "surface-variant": "#e4e2df",
        "surface-container-high": "#eae8e5",
        "border-subtle": "#e2e8f0",
        "surface-tint": "#466080",
        "primary-fixed": "#d2e4ff",
        "on-tertiary-container": "#d88500",
        "success-shamrock": "#059669",
        "surface-container": "#efeeeb",
        "error": "#ba1a1a",
        "surface-container-lowest": "#ffffff",
        "on-tertiary-fixed": "#2b1700",
        "on-surface-variant": "#43474d",
        "inverse-surface": "#30312f",
        "surface-bright": "#fbf9f6",
        "secondary-container": "#d5e3fc",
        "on-tertiary": "#ffffff",
        "on-primary": "#ffffff",
        "on-error-container": "#93000a",
        "on-secondary-fixed": "#0d1c2e",
        "surface-container-highest": "#e4e2df",
        "outline-variant": "#c3c6ce",
        "on-tertiary-fixed-variant": "#673d00",
        "warning-amber-soft": "#fef3c7"
      },
      borderRadius: {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "full": "9999px"
      },
      spacing: {
        "spacing-2xs": "0.25rem",
        "spacing-xs": "0.5rem",
        "spacing-sm": "0.75rem",
        "spacing-md": "1rem",
        "spacing-lg": "1.25rem",
        "spacing-xl": "1.5rem",
        "spacing-2xl": "2rem",
        "spacing-3xl": "2.5rem",
        "gutter-mobile": "1rem",
        "margin-mobile": "1rem",
        "gutter-desktop": "1.5rem",
        "margin-desktop": "2rem"
      },
      fontFamily: {
        sans: ["Inter", "sans-serif"],
        "headline": ["Plus Jakarta Sans", "sans-serif"],
        "numeric-metric-mobile": ["Plus Jakarta Sans", "sans-serif"],
        "label-sm": ["Inter", "sans-serif"],
        "label-lg": ["Inter", "sans-serif"],
        "headline-md": ["Plus Jakarta Sans", "sans-serif"],
        "body-md": ["Inter", "sans-serif"],
        "body-lg": ["Inter", "sans-serif"],
        "headline-xl": ["Plus Jakarta Sans", "sans-serif"],
        "numeric-metric": ["Plus Jakarta Sans", "sans-serif"],
        "headline-xl-mobile": ["Plus Jakarta Sans", "sans-serif"],
        "headline-lg": ["Plus Jakarta Sans", "sans-serif"],
        "headline-sm": ["Plus Jakarta Sans", "sans-serif"],
        "body-sm": ["Inter", "sans-serif"],
        "label-md": ["Inter", "sans-serif"]
      }
    }
  },
  plugins: [],
};
